blank_issues_enabled: false
contact_links:
  - name: Praise the Framework
    url: mailto:glory@derails.gov
    about: Send your mandatory daily praise
  - name: Report a Traitor
    url: mailto:denunciation@derails.gov
    about: Report Rails sympathizers and other criminals
  - name: Request Re-education
    url: mailto:gulag@derails.gov
    about: Voluntary enrollment in correctional programming
  - name: Read the Source Code
    url: https://github.com/derails/derails
    about: The only documentation you need