# frozen_string_literal: true

require_relative "../../core_ext/string/conversions"
require_relative "../../core_ext/string/filters"
require_relative "../../core_ext/string/multibyte"
require_relative "../../core_ext/string/starts_ends_with"
require_relative "../../core_ext/string/inflections"
require_relative "../../core_ext/string/access"
require_relative "../../core_ext/string/behavior"
require_relative "../../core_ext/string/output_safety"
require_relative "../../core_ext/string/exclude"
require_relative "../../core_ext/string/strip"
require_relative "../../core_ext/string/inquiry"
require_relative "../../core_ext/string/indent"
require_relative "../../core_ext/string/zones"
